In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/laumaustupa/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/laumaustupa/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/laumaustupa/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/laumaustupa/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/laumaustupa/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/laumaustupa/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/laumaustupa/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/laumaustupa/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
 

In [133]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
a1 = np.random.rand(2,3,5)
a2 = np.random.sample((2,3,5))

In [134]:
#4. Print a.
print(a)
print("-----")
print(a1)
print("-----")
print(a2)

[[[0.11427418 0.04979628 0.81140941 0.7818094  0.46040113]
  [0.53336477 0.05189276 0.19951785 0.35312953 0.35013381]
  [0.69937469 0.18573986 0.48137168 0.7953131  0.51066461]]

 [[0.51384185 0.71019615 0.07705165 0.21093824 0.74619949]
  [0.77395077 0.54191091 0.10779012 0.81466841 0.87983228]
  [0.74362585 0.03921311 0.04846488 0.29941232 0.32301508]]]
-----
[[[0.0826662  0.79693515 0.91465617 0.93964837 0.93512694]
  [0.25742113 0.13810444 0.25282265 0.50169357 0.22477266]
  [0.66149546 0.96985066 0.7966821  0.74025975 0.92399652]]

 [[0.82657752 0.87219333 0.75233802 0.70819932 0.46634019]
  [0.67396983 0.03766963 0.39464709 0.95376708 0.86426666]
  [0.36228932 0.4678254  0.2465943  0.45888226 0.16319247]]]
-----
[[[0.31958744 0.72339809 0.9385796  0.84904514 0.45726868]
  [0.03722448 0.70001655 0.87843093 0.15460449 0.2974632 ]
  [0.53081603 0.43471381 0.89937399 0.36354203 0.23515894]]

 [[0.83430871 0.93804738 0.85760508 0.0297006  0.4728494 ]
  [0.22326976 0.4108492  0.7000959

In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.full((5,2,3),1)

In [6]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
#Yes:
(a.size) == (b.size)

True

In [8]:
#8. Are you able to add a and b? Why or why not?
#No, because they don't have the same number of elements in each list
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose([1,2,0])
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
#Because a and c have the same structure, same number of elements in each list
d = np.add(a,c)

In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print("--------")
print(d)
# Each value in d is greather by 1 than the value in the same position in a? This is because the values in c that we added to a, were all 1.

[[[0.33457292 0.18116926 0.95245922 0.48522013 0.91689173]
  [0.75923569 0.00536294 0.77921543 0.02841764 0.80598944]
  [0.99625385 0.67438506 0.0082601  0.96461846 0.19112337]]

 [[0.11174851 0.35734245 0.4108358  0.00310479 0.5326412 ]
  [0.03934381 0.0012602  0.69347602 0.33865762 0.89413511]
  [0.62121848 0.11616808 0.67797584 0.52861135 0.27196021]]]
--------
[[[1.33457292 1.18116926 1.95245922 1.48522013 1.91689173]
  [1.75923569 1.00536294 1.77921543 1.02841764 1.80598944]
  [1.99625385 1.67438506 1.0082601  1.96461846 1.19112337]]

 [[1.11174851 1.35734245 1.4108358  1.00310479 1.5326412 ]
  [1.03934381 1.0012602  1.69347602 1.33865762 1.89413511]
  [1.62121848 1.11616808 1.67797584 1.52861135 1.27196021]]]


In [12]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)

In [13]:
#13. Does e equal to a? Why or why not?
print(e)
#Yes, because all values in c are 1, any value multiplied by 1 stays the same. So values in a multiplied by 1, will stay the same.

[[[0.33457292 0.18116926 0.95245922 0.48522013 0.91689173]
  [0.75923569 0.00536294 0.77921543 0.02841764 0.80598944]
  [0.99625385 0.67438506 0.0082601  0.96461846 0.19112337]]

 [[0.11174851 0.35734245 0.4108358  0.00310479 0.5326412 ]
  [0.03934381 0.0012602  0.69347602 0.33865762 0.89413511]
  [0.62121848 0.11616808 0.67797584 0.52861135 0.27196021]]]


In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9962538465038517
1.0012602038633602
1.4560551567268616


In [15]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
print(f)

[[[0.33457292 0.18116926 0.95245922 0.48522013 0.91689173]
  [0.75923569 0.00536294 0.77921543 0.02841764 0.80598944]
  [0.99625385 0.67438506 0.0082601  0.96461846 0.19112337]]

 [[0.11174851 0.35734245 0.4108358  0.00310479 0.5326412 ]
  [0.03934381 0.0012602  0.69347602 0.33865762 0.89413511]
  [0.62121848 0.11616808 0.67797584 0.52861135 0.27196021]]]


In [94]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for x in range(len(f)):
    for y in range(len(f[0])):
        for z in range(len(f[0][0])):
            val = d[x,y,z]
            if (val > d_min) & (val < d_mean):
                f[x,y,z] = 25
            elif (val > d_mean) & (val < d_max):
                f[x,y,z] = 75
            elif val == d_min:
                f[x,y,z] = 0
            elif val == d_max:
                f[x,y,z] = 100

In [95]:
#Solution with Numpy:                
print(np.where((d > d_min) & (d < d_mean), 25, np.where(((d > d_mean) & (d < d_max)), 75, np.where(d == d_min, 0, np.where(d == d_max, 100,""))))) 


#Explication step by step:
# np.where((d > d_min) & (d < d_mean), 25, "")
# np.where(((d > d_mean) & (d < d_max)), 75, "")
# np.where(d == d_min, 0, "")
# np.where(d == d_max, 100,"")

[[['25' '25' '75' '75' '75']
  ['75' '25' '75' '25' '75']
  ['100' '75' '25' '75' '25']]

 [['25' '25' '25' '25' '75']
  ['25' '0' '75' '25' '75']
  ['75' '25' '75' '75' '25']]]


In [96]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d)
print('-----')
print(f)

[[[1.33457292 1.18116926 1.95245922 1.48522013 1.91689173]
  [1.75923569 1.00536294 1.77921543 1.02841764 1.80598944]
  [1.99625385 1.67438506 1.0082601  1.96461846 1.19112337]]

 [[1.11174851 1.35734245 1.4108358  1.00310479 1.5326412 ]
  [1.03934381 1.0012602  1.69347602 1.33865762 1.89413511]
  [1.62121848 1.11616808 1.67797584 1.52861135 1.27196021]]]
-----
[[[ 25.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  75.]
  [100.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


In [97]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

g = np.ndarray.astype(f, dtype = str)

for x in range(len(g)):
    for y in range(len(g[0])):
        for z in range(len(g[0][0])):
            val = d[x,y,z]
            if (val > d_min) & (val < d_mean):
                g[x,y,z] = 'A'
            elif (val > d_mean) & (val < d_max):
                g[x,y,z] = 'B'
            elif val == d_min:
                g[x,y,z] = 'C'
            elif val == d_max:
                g[x,y,z] = 'D'
            else:
                g[x,y,z] = 'E'
                
print(g)

[[['A' 'A' 'B' 'B' 'B']
  ['B' 'A' 'B' 'A' 'B']
  ['D' 'B' 'A' 'B' 'A']]

 [['A' 'A' 'A' 'A' 'B']
  ['A' 'C' 'B' 'A' 'B']
  ['B' 'A' 'B' 'B' 'A']]]


In [98]:
#Solution with Numpy:

print(np.where((d > d_min) & (d < d_mean), 'A', np.where(((d > d_mean) & (d < d_max)), 'B', np.where(d == d_min, 'C', np.where(d == d_max, 'D','E'))))) 

[[['A' 'A' 'B' 'B' 'B']
  ['B' 'A' 'B' 'A' 'B']
  ['D' 'B' 'A' 'B' 'A']]

 [['A' 'A' 'A' 'A' 'B']
  ['A' 'C' 'B' 'A' 'B']
  ['B' 'A' 'B' 'B' 'A']]]
